'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SGAS.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property BG_AboutUs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG_AboutUs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BG_AreaG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG_AreaG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BG_Att() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG_Att", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BG_Attendance() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG_Attendance", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BG_Cat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG_Cat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BG_Cat1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG_Cat1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BG_CL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG_CL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BG_Class() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG_Class", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BG_Comp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG_Comp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BG_Course() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG_Course", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BG_Flash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG_Flash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BG_GS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG_GS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BG_Items() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG_Items", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BG_LogIn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG_LogIn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BG_LogIn1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG_LogIn1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BG_LogInNEW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG_LogInNEW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BG_Main() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG_Main", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BG_MainRevised() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG_MainRevised", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BG_MainRevised1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG_MainRevised1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BG_NO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG_NO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BG_Other() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG_Other", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BG_Other1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG_Other1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BG_Section() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG_Section", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BG_Stud() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG_Stud", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BG_Sub() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG_Sub", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BG_User() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG_User", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BG_VOG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG_VOG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Butones() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Butones", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Glass_Bar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Glass_Bar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SGAS_SPLASH_New() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SGAS SPLASH New", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
